stages:
    - test_run
    - test_run_report

services:
    - docker:24

run_tests_in_chrome_browser:
    when: manual
    stage: test_run
    image: docker:24
    script:
        # Проверяем наличие докерфайла в репозитории 
        - ls -la
        # Запускаем прогон тестов в контейнере
        - docker compose up run_tests_in_chrome --exit-code-from run_tests_in_chrome || true
    after_script:
        - docker compose up report
        - echo "Report path:https://aleksei_mishin.gitlab.io/-/TestShopQA/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"
    artifacts:
        when: on_success
        expire_in: 10 days
        paths:
            - allure-report

run_tests_in_firefox_browser:
    when: manual
    stage: test_run
    image: docker:24
    script:
        # Проверяем наличие докерфайла в репозитории 
        - ls -la
        # Запускаем прогон тестов в контейнере
        - docker compose up run_tests_in_firefox --exit-code-from run_tests_in_firefox || true
    after_script:
        - docker compose up report
        - echo "Report path:https://aleksei_mishin.gitlab.io/-/TestShopQA/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"
    artifacts:
        when: on_success
        expire_in: 10 days
        paths:
            - allure-report

# chrome_pages:
#   stage: test_run_report
#   needs:
#     - run_tests_in_chrome_browser
#   script:
#     - mkdir public
#     - cp -r allure-report/* public
#   artifacts:
#     when: on_success
#     expire_in: never
#     paths:
#       - public

# firefox_pages:
#   stage: test_run_report
#   needs:
#     - run_tests_in_firefox_browser
#   script:
#     - mkdir public
#     - cp -r allure-report/* public
#   artifacts:
#     when: on_success
#     expire_in: never
#     paths:
#       - public
    