class ProductPageLocators:
    PRODUCT_TITLE = ('css selector', '[itemprop="name"]')
    PRODUCT_PRICE = ('css selector', '[class="oe_price"]')
    ADD_TO_CART_BUTTON = ('css selector', '[id="add_to_cart"]')
    ADD_ONE_BUTTON = ('css selector', '[id="o_wsale_cta_wrapper"] [title="Add one"]')
    REMOVE_ONE_BUTTON = ('css selector', '[id="o_wsale_cta_wrapper"] [title="Remove one"]')
    QUANTITY_INPUT = ('css selector', '[id="o_wsale_cta_wrapper"] [name="add_qty"]')
    RADIO_BUTTON_MATERIAL = ('css selector', '[type="radio"][data-attribute_name="Legs"]')
    RADIO_BUTTON_COLOR = ('css selector', '[type="radio"][data-attribute_name="Color"]')
    PRODUCT_DESCRIPTION = ('xpath', '//*[contains(@placeholder, "A short description")]')
